/**
 * Neutral prompts for calibration sessions.
 * These should elicit real writing (not one-word answers) without
 * emotional charge. The system picks one at random each time.
 *
 * Categories: daily routines, food, environment, objects, errands,
 * movement, weather, media, process descriptions, observations.
 *
 * All prompts are designed to produce knowledge-telling (reciting known facts),
 * not knowledge-transforming (generating new understanding). This makes
 * calibration sessions the floor for KT detection.
 */
export const CALIBRATION_PROMPTS: string[] = [
  // --- Daily routines ---
  "Describe what you did this morning in as much detail as you can remember.",
  "What's your morning routine from the moment you wake up?",
  "What's something you do every single day without thinking about it? Describe the routine.",
  "Walk through the last hour before you went to bed last night.",
  "Describe what you did between getting home and eating dinner yesterday.",
  "What does your typical Sunday look like?",
  "Walk through your morning hygiene routine step by step.",
  "Describe the first 30 minutes after you wake up on a workday.",
  "What do you usually do right after lunch?",
  "Describe your evening wind-down routine.",
  "What's the last thing you do before leaving the house?",
  "Walk through how you get ready when you're running late.",
  "Describe your routine when you get to your desk or workspace.",
  "What do you do during your lunch break on a typical day?",
  "Describe how you typically end your workday.",

  // --- Food ---
  "What did you eat yesterday? Walk through it meal by meal.",
  "Walk through how you make your favorite meal, step by step.",
  "Describe the last thing you cooked. What steps did you follow?",
  "What's in your fridge right now? List what you can remember.",
  "Describe the last meal you ate at a restaurant. What did you order?",
  "What did you have for breakfast this week? Walk through each day.",
  "Describe how you make your morning coffee or tea.",
  "What's your go-to snack? Describe what it looks like and how you eat it.",
  "Walk through the last time you went grocery shopping. What did you buy?",
  "Describe the last takeout or delivery you ordered.",
  "What's a meal you make when you don't feel like cooking? Describe it.",
  "Walk through how you pack a lunch if you bring one.",
  "Describe the last time you tried something new to eat.",
  "What's the most complicated thing you've cooked recently? Walk through it.",
  "Describe what you typically drink throughout the day.",

  // --- Environment ---
  "Describe the room you're sitting in right now.",
  "What's on your desk or table right now? List everything you can see.",
  "Describe the view from your window right now.",
  "Describe the weather today and how it changed throughout the day.",
  "Look around and describe three objects within arm's reach.",
  "Describe the lighting in the room you're in right now.",
  "What sounds can you hear right now? List them all.",
  "Describe the floor in the room you're in. What's on it?",
  "What's on the walls of the room you're in?",
  "Describe the temperature right now and how it feels.",
  "Look at the nearest shelf or surface. Describe what's on it.",
  "Describe the building you're in from the outside.",
  "What does the street outside look like right now?",
  "Describe the nearest plant or tree you can see.",
  "What's the most cluttered area in your space right now? Describe it.",
  "Describe the ceiling above you.",
  "What can you see through the nearest window?",
  "Describe the entrance to where you live.",
  "What does your kitchen counter look like right now?",
  "Describe the closest door to you in detail.",

  // --- Objects ---
  "Describe the last thing you bought and why you bought it.",
  "What's in your pockets or bag right now?",
  "Describe the phone or device you're using right now.",
  "What's the oldest thing you own that you still use? Describe it.",
  "Describe the shoes you wore today.",
  "What's the last thing you threw away? Describe it.",
  "Describe the chair or seat you're sitting in right now.",
  "What's the newest thing in the room you're in?",
  "Describe your keys and what's on your keychain.",
  "What's the most worn-out thing you still use? Describe its condition.",
  "Describe the cup or glass nearest to you.",
  "What does your wallet or cardholder look like?",
  "Describe the last piece of clothing you put on today.",
  "What's the heaviest thing within arm's reach?",
  "Describe your toothbrush. Color, condition, where you keep it.",
  "What's the smallest object you can see right now? Describe it.",
  "Describe the last thing you received in the mail.",
  "What does your bedside table or nightstand look like?",
  "Describe the trash can nearest to you. What's in it?",
  "What's the most colorful thing in your field of vision?",

  // --- Errands and logistics ---
  "Describe your commute or your typical route when you leave the house.",
  "Walk through the last errand you ran.",
  "Describe the last time you went to a store. What was it like inside?",
  "What's on your to-do list for tomorrow? Walk through it.",
  "Describe the last time you had to wait in line somewhere.",
  "Walk through how you do your laundry.",
  "Describe the last time you cleaned something.",
  "What bills or payments do you deal with on a regular basis?",
  "Describe the last time you had to deal with customer service.",
  "Walk through the last time you filled up your car or charged your vehicle.",
  "Describe the parking situation where you live or work.",
  "What's the last appointment you went to? Walk through arriving.",
  "Describe the last time you packed for something — a trip, a gym bag, anything.",
  "Walk through how you organize your week.",
  "Describe the last time you had to fix something around the house.",

  // --- Movement and places ---
  "Describe the last walk you took. Where did you go?",
  "What does the area around where you live look like?",
  "Describe the last time you exercised or moved your body.",
  "Walk through the route from your front door to the nearest store.",
  "Describe the last public place you sat down in.",
  "What does your neighborhood sound like at night?",
  "Describe the last time you drove or rode somewhere new.",
  "Walk through the layout of your home, room by room.",
  "Describe the nearest intersection to where you are.",
  "What's the closest body of water to where you live? Describe it.",
  "Describe the last elevator or staircase you used.",
  "Walk through what it's like to enter your building.",
  "Describe the hallway or path to your front door.",
  "What does the nearest park or green space look like?",
  "Describe the last time you were in a car. Where were you going?",

  // --- Weather and seasons ---
  "Describe what the sky looks like right now.",
  "What was the weather like when you woke up this morning?",
  "Describe the last time it rained where you are.",
  "What does this time of year feel like where you live?",
  "Describe the last sunset or sunrise you noticed.",
  "What was the temperature like when you walked outside today?",
  "Describe what the wind is like right now.",
  "What did the sky look like on your way home today?",
  "Describe the last time you noticed the moon.",
  "What season does it feel like right now? Describe why.",

  // --- Media and entertainment ---
  "What's the last show or movie you watched? What happened in it?",
  "Describe the last song you listened to. What did it sound like?",
  "What's the last thing you read? Describe what it was about.",
  "Walk through the last YouTube video or clip you watched.",
  "Describe the last podcast or audio you listened to.",
  "What's the last game you played? Describe what happened.",
  "Walk through the last social media scroll session you had. What did you see?",
  "Describe the last notification you got on your phone.",
  "What's the last photo you took? Describe what's in it.",
  "Describe the last ad you remember seeing.",

  // --- Conversations and people ---
  "Describe the last conversation you had with someone today.",
  "What's the last text message you sent? What was it about?",
  "Describe the last person you spoke to face-to-face. What were they wearing?",
  "Walk through the last phone call you made or received.",
  "Describe the last time someone asked you for help with something.",
  "What's the last compliment you received or gave?",
  "Describe the last time you said goodbye to someone today.",
  "Walk through the last meeting or group interaction you had.",
  "Describe the cashier or service person you last interacted with.",
  "What's the last thing someone recommended to you?",

  // --- Process descriptions ---
  "Walk through how you unlock and open your phone.",
  "Describe how you wash your hands. Every step.",
  "Walk through how you make your bed.",
  "Describe the process of starting your computer or device.",
  "Walk through how you parallel park or park your car.",
  "Describe how you fold a shirt.",
  "Walk through the steps you take to lock up when you leave home.",
  "Describe how you brush your teeth. Be specific.",
  "Walk through how you set an alarm.",
  "Describe how you check the weather each day.",
  "Walk through how you charge your phone at night.",
  "Describe how you sort your mail or packages.",
  "Walk through how you take out the trash.",
  "Describe how you adjust the temperature in your home.",
  "Walk through the steps of making a sandwich.",

  // --- Memory recall ---
  "What did you do exactly one week ago today? Try to remember.",
  "Describe the last store you walked into. What was the layout like?",
  "What was the last thing you searched for online?",
  "Describe the last time you ate outside.",
  "What did you wear yesterday?",
  "Describe the last time you used cash.",
  "What was the first thing you saw when you opened your eyes this morning?",
  "Describe the last drink of water you had. Where were you?",
  "What's the last thing you microwaved or heated up?",
  "Describe the last time you looked at the time. What were you doing?",
  "What was the last door you walked through before sitting down?",
  "Describe the last time you washed dishes.",
  "What was playing in the background the last time you ate?",
  "Describe the last time you stretched.",
  "What's the last thing you picked up off the floor?",

  // --- Numbers and lists ---
  "How many windows are in the room you're in? Describe each one.",
  "Count the light sources in your room. Describe them.",
  "How many steps is it from where you're sitting to the nearest door?",
  "List everything you can see that's blue.",
  "How many apps did you open on your phone today? Name them.",
  "Count the books or magazines you can see. Describe their covers.",
  "List everything you ate and drank today in order.",
  "How many times did you leave the house today? Where did you go each time?",
  "Count the electronics in the room. Describe what each one does.",
  "List every surface in the room you're in.",
];
