import { SEED_QUESTIONS } from './seeds.ts';
import { scheduleQuestion, hasQuestionForDate } from './db.ts';
import { localDateStr } from './date.ts';

/**
 * Seeds the next N days with questions from the seed list.
 * Skips dates that already have a question (e.g., generated by the nightly job).
 */
export function seedUpcomingQuestions(days = 30): void {
  const today = new Date();

  for (let i = 0; i < days && i < SEED_QUESTIONS.length; i++) {
    const date = new Date(today);
    date.setDate(today.getDate() + i);
    const dateStr = localDateStr(date);

    if (!hasQuestionForDate(dateStr)) {
      scheduleQuestion(SEED_QUESTIONS[i], dateStr, 'seed');
    }
  }
}
