/* eslint-disable */
/* prettier-ignore */
// Auto-generated by src-rs/scripts/generate-dts.mjs from napi-derive type-def output.
// DO NOT EDIT BY HAND. Edit the Rust #[napi] annotations and rebuild.

export interface KeystrokeEventInput {
  /** Key character / code */
  c: string
  /** Key-down offset (ms) */
  d: number
  /** Key-up offset (ms) */
  u: number
}

export interface DynamicalSignals {
  ikiCount: number
  holdFlightCount: number
  permutationEntropy?: number
  permutationEntropyRaw?: number
  peSpectrum?: Array<number>
  dfaAlpha?: number
  mfdfaSpectrumWidth?: number
  mfdfaAsymmetry?: number
  mfdfaPeakAlpha?: number
  temporalIrreversibility?: number
  ikiPsdSpectralSlope?: number
  ikiPsdRespiratoryPeakHz?: number
  peakTypingFrequencyHz?: number
  ikiPsdLfHfRatio?: number
  ikiPsdFastSlowVarianceRatio?: number
  statisticalComplexity?: number
  forbiddenPatternFraction?: number
  weightedPe?: number
  lempelZivComplexity?: number
  optnTransitionEntropy?: number
  optnForbiddenTransitionCount?: number
  rqaDeterminism?: number
  rqaLaminarity?: number
  rqaTrappingTime?: number
  rqaRecurrenceRate?: number
  rqaRecurrenceTimeEntropy?: number
  rqaMeanRecurrenceTime?: number
  recurrenceTransitivity?: number
  recurrenceAvgPathLength?: number
  recurrenceClustering?: number
  recurrenceAssortativity?: number
  effectiveInformation?: number
  causalEmergenceIndex?: number
  optimalCausalScale?: number
  pidSynergy?: number
  pidRedundancy?: number
  branchingRatio?: number
  avalancheSizeExponent?: number
  dmdDominantFrequency?: number
  dmdDominantDecayRate?: number
  dmdModeCount?: number
  dmdSpectralEntropy?: number
  pauseMixtureComponentCount?: number
  pauseMixtureMotorProportion?: number
  pauseMixtureCognitiveLoadIndex?: number
  teHoldToFlight?: number
  teFlightToHold?: number
  teDominance?: number
}

/**
 * One (digraph, latency) pair from the digraph latency profile. Returned as
 * a sorted `Vec<DigraphEntry>` so iteration is deterministic — pre-2026-04-25
 * this crossed the boundary as a JSON-stringified `Record<string, number>`,
 * which forced the Rust side to maintain a `BTreeMap` purely for
 * serialization-order determinism. The typed Vec carries the determinism
 * guarantee in the data structure itself.
 */
export interface DigraphEntry {
  /** Two-character digraph encoded as `prev>next` (e.g. `"t>h"`). */
  digraph: string
  /** Mean flight time across all observations of this digraph (ms). */
  latencyMs: number
}

export interface MotorSignals {
  sampleEntropy?: number
  mseSeries?: Array<number>
  complexityIndex?: number
  exGaussianFisherTrace?: number
  ikiAutocorrelation?: Array<number>
  motorJerk?: number
  lapseRate?: number
  tempoDrift?: number
  ikiCompressionRatio?: number
  /**
   * Top-10 digraphs by frequency (sorted by count desc, then key asc for
   * deterministic tie-breaking). `None` if the stream is too short to
   * observe any digraph at least twice.
   */
  digraphLatencyProfile?: Array<DigraphEntry>
  exGaussianTau?: number
  exGaussianMu?: number
  exGaussianSigma?: number
  tauProportion?: number
  adjacentHoldTimeCov?: number
  holdFlightRankCorr?: number
}

export interface RBurstEntry {
  deletedCharCount: number
  totalCharCount: number
  durationMs: number
  startOffsetMs: number
  isLeadingEdge: boolean
}

export interface ProcessSignals {
  pauseWithinWord?: number
  pauseBetweenWord?: number
  pauseBetweenSentence?: number
  abandonedThoughtCount?: number
  rBurstCount?: number
  iBurstCount?: number
  rBurstSequences: Array<RBurstEntry>
  vocabExpansionRate?: number
  phaseTransitionPoint?: number
  strategyShiftCount?: number
}

/**
 * One (digraph, mean_latency_ms) pair from the personal-profile aggregate.
 * Shape mirrors `DigraphEntry` for the per-session output, but the semantic
 * meaning differs: this is the long-term aggregate across all sessions, used
 * by the avatar timing synthesis to look up expected latency for a given
 * bigram during generation.
 */
export interface DigraphAggregateEntry {
  digraph: string
  meanLatencyMs: number
}

/**
 * Typed napi mirror of the personal motor profile loaded by the avatar
 * pipeline. Pre-2026-04-25 this crossed the FFI as a heterogeneous JSON
 * string built in `libReconstruction.ts` and parsed by `serde_json` in
 * avatar.rs. Typing the boundary forces an explicit Rust+TS update for
 * every new profile field — silent profile-schema evolution (where the
 * TS side adds a field that Rust silently ignores) is no longer possible.
 *
 * Internal avatar.rs still consumes a JSON string (preserves the 1900-line
 * internal API). The napi entry points serialize this struct to JSON before
 * delegating; the cost of one re-serialization is bounded and the schema
 * guarantee is what matters.
 */
export interface AvatarProfileInput {
  /**
   * Top-K digraphs by frequency, with mean latency. Used as a per-bigram
   * timing lookup during text generation.
   */
  digraph?: Array<DigraphAggregateEntry>
  /** Ex-Gaussian mu (Gaussian mean of IKI distribution) */
  mu?: number
  /** Ex-Gaussian sigma */
  sigma?: number
  /** Ex-Gaussian tau (exponential tail; attentional lapses) */
  tau?: number
  /** Mean P-burst length in chars */
  burstLength?: number
  /** Proportion of pauses at word boundaries */
  pauseBetweenPct?: number
  /** Proportion of pauses at sentence boundaries */
  pauseSentPct?: number
  /** First keystroke latency in ms */
  firstKeystroke?: number
  smallDelRate?: number
  largeDelRate?: number
  revisionTimingBias?: number
  rBurstRatio?: number
  rburstMeanSize?: number
  rburstLeadingEdgePct?: number
  rburstConsolidation?: number
  rburstMeanDuration?: number
  ikiAutocorrelationLag1?: number
  holdFlightRankCorrelation?: number
  holdTimeMean?: number
  holdTimeStd?: number
  flightTimeMean?: number
  flightTimeStd?: number
}

export interface AvatarOutput {
  /** Generated text from Markov chain */
  text: string
  /** Per-character delay in ms */
  delays: Array<number>
  /**
   * Synthetic keystroke stream as JSON (array of {c, d, u} events).
   * Can be passed directly to the signal pipeline for validation.
   */
  keystrokeStreamJson: string
  /** Word count of generated text */
  wordCount: number
  /** Markov order used (1 or 2, or PPM max_depth for PPM variants) */
  order: number
  /** Number of unique states in the chain */
  chainSize: number
  /**
   * Number of I-burst episodes injected. Cannot be detected from the
   * flat keystroke stream; must be returned as metadata.
   */
  iBurstCount: number
  /** Which adversary variant produced this result (1-5). */
  variant: number
  /**
   * PRNG seed used for this generation (u64 as decimal string).
   * Store this to reproduce the exact same ghost via `regenerate_avatar`.
   * Serialized as a string because JS Number loses precision above 2^53.
   */
  seed: string
}

export interface PerplexityOutput {
  /** Per-word log2 perplexity (lower = model predicts the text better) */
  perplexity: number
  /** Number of words evaluated */
  wordCount: number
  /** Fraction of transitions that were known to the chain (0.0 to 1.0) */
  knownFraction: number
}

export interface ProfileDistanceOutput {
  /** Per-dimension z-scores (only dimensions with std > 0) */
  zScores: Array<number>
  /** L2 norm of z-scores */
  distance: number
  /** How many dimensions contributed */
  dimensionCount: number
}

export interface CorrelationResult {
  /** Index of the first series (emotion dimension) */
  aIndex: number
  /** Index of the second series (behavior dimension) */
  bIndex: number
  /** Window size used */
  windowSize: number
  /** Best lagged Pearson correlation */
  correlation: number
  /** Lag at which best correlation was found */
  lag: number
}

export declare function computeDynamicalSignals(stream: Array<KeystrokeEventInput>): DynamicalSignals

export declare function computeMotorSignals(stream: Array<KeystrokeEventInput>, totalDurationMs: number): MotorSignals

export declare function computeProcessSignals(eventLogJson: string): ProcessSignals

/**
 * Generate text from a personal corpus Markov chain with timing from a motor profile.
 *
 * Inputs are typed at the napi boundary (`Vec<String>` for the corpus,
 * `AvatarProfileInput` for the profile). Internally re-serialized to the
 * JSON form that `avatar::compute` consumes; this preserves the avatar's
 * existing internal API while moving schema-evolution defense to the FFI.
 */
export declare function generateAvatar(corpus: Array<string>, topic: string, profile: AvatarProfileInput, maxWords: number, variant: number): AvatarOutput

/**
 * Regenerate a ghost from a stored seed for reproducibility verification.
 *
 * Identical to `generate_avatar` except the PRNG seed is provided explicitly
 * (as a decimal string, since JS cannot represent u64 without precision loss)
 * instead of being derived from `SystemTime`. Given the same inputs and seed,
 * the output is bit-identical to the original generation.
 */
export declare function regenerateAvatar(corpus: Array<string>, topic: string, profile: AvatarProfileInput, maxWords: number, variant: number, seed: string): AvatarOutput

/**
 * Compute profile distance: z-score each dimension against profile means/stds,
 * return L2 norm. Used for mediation detection (flagging anomalous sessions).
 */
export declare function computeProfileDistance(values: Array<number>, means: Array<number>, stds: Array<number>): ProfileDistanceOutput

/**
 * Batch-compute lagged Pearson correlations between all pairs of
 * series_a and series_b at multiple window sizes. Returns only pairs
 * exceeding the threshold. Used for coupling stability analysis.
 *
 * `series_a_json`: JSON array of arrays (e.g., 9 emotion dims x N entries)
 * `series_b_json`: JSON array of arrays (e.g., 7 behavior dims x N entries)
 * `window_sizes_json`: JSON array of window sizes to test
 * `max_lag`: maximum lag to test
 * `threshold`: minimum |r| to include in results
 */
export declare function computeBatchCorrelations(seriesA: Array<Array<number>>, seriesB: Array<Array<number>>, windowSizes: Array<number>, maxLag: number, threshold: number): Array<CorrelationResult>

/**
 * Compute perplexity of a text against the corpus Markov model.
 * Tracks convergence: as the corpus grows, perplexity of real journal
 * responses should decrease monotonically.
 */
export declare function computePerplexity(corpus: Array<string>, text: string): PerplexityOutput
