export const calibrationPrompts: { text: string; type: "calibration" }[] = [
  { text: "Describe a paperclip to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tie a shoe.", type: "calibration" },
  { text: "Describe a fork without using the words \"eat,\" \"food,\" or \"metal.\"", type: "calibration" },
  { text: "Name as many animals as you can in 60 seconds.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a street scene from a city you don't recognize]", type: "calibration" },
  { text: "Describe the taste of water to someone who has never had it.", type: "calibration" },
  { text: "Describe the room you're in as if writing stage directions.", type: "calibration" },
  { text: "Describe the feel of a piece of silk to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of coffee brewing to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of rain on a window to someone who has never heard it.", type: "calibration" },
  { text: "Describe a stapler to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tie a necktie.", type: "calibration" },
  { text: "Describe a spoon without using the words \"eat,\" \"soup,\" or \"round.\"", type: "calibration" },
  { text: "Name as many four-legged animals as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a landscape without any people in it]", type: "calibration" },
  { text: "Describe the taste of plain white rice to someone who has never had it.", type: "calibration" },
  { text: "Describe the room you're in as if narrating for an audiobook.", type: "calibration" },
  { text: "Describe the feel of raw denim to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of bread baking to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of rain on a metal roof to someone who has never heard it.", type: "calibration" },
  { text: "Describe a rubber band to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tie a bow tie.", type: "calibration" },
  { text: "Describe a knife without using the words \"cut,\" \"sharp,\" or \"blade.\"", type: "calibration" },
  { text: "Name as many animals that fly as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a still life arrangement of fruit and vessels]", type: "calibration" },
  { text: "Describe the taste of unseasoned chicken breast to someone who has never had it.", type: "calibration" },
  { text: "Describe the room you're in from the perspective of a ceiling camera.", type: "calibration" },
  { text: "Describe the feel of velvet to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of bacon cooking to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a creaking floorboard to someone who has never heard it.", type: "calibration" },
  { text: "Describe a zipper to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tie a scarf.", type: "calibration" },
  { text: "Describe a cup without using the words \"drink,\" \"hold,\" or \"liquid.\"", type: "calibration" },
  { text: "Name as many animals that swim as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a cluttered desk viewed from above]", type: "calibration" },
  { text: "Describe the taste of a ripe banana to someone who has never had it.", type: "calibration" },
  { text: "Describe the room you're in from knee height.", type: "calibration" },
  { text: "Describe the feel of corduroy to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of onions being sautéed to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a door slamming to someone who has never heard it.", type: "calibration" },
  { text: "Describe a button to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tie a bowline knot.", type: "calibration" },
  { text: "Describe a plate without using the words \"food,\" \"round,\" or \"flat.\"", type: "calibration" },
  { text: "Name as many animals that live underground as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a single object on a plain background]", type: "calibration" },
  { text: "Describe the taste of a green banana to someone who has never had it.", type: "calibration" },
  { text: "Describe the view out the nearest window.", type: "calibration" },
  { text: "Describe the feel of wet wool to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of garlic in olive oil to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a door closing softly to someone who has never heard it.", type: "calibration" },
  { text: "Describe a safety pin to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tie a square knot.", type: "calibration" },
  { text: "Describe a bowl without using the words \"soup,\" \"round,\" or \"hold.\"", type: "calibration" },
  { text: "Name as many nocturnal animals as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a close-up of a texture like bark, fabric, or stone]", type: "calibration" },
  { text: "Describe the taste of an overripe banana to someone who has never had it.", type: "calibration" },
  { text: "Describe the light in the room you're in right now.", type: "calibration" },
  { text: "Describe the feel of dry wool to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of fresh basil to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a key turning in a lock to someone who has never heard it.", type: "calibration" },
  { text: "Describe a thumbtack to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to crack an egg.", type: "calibration" },
  { text: "Describe a table without using the words \"flat,\" \"legs,\" or \"surface.\"", type: "calibration" },
  { text: "Name as many farm animals as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a portrait of a stranger in neutral lighting]", type: "calibration" },
  { text: "Describe the taste of a raw carrot to someone who has never had it.", type: "calibration" },
  { text: "Describe the temperature and air quality in the room you're in.", type: "calibration" },
  { text: "Describe the feel of a cashmere sweater to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a ripe tomato on the vine to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of footsteps on gravel to someone who has never heard it.", type: "calibration" },
  { text: "Describe a binder clip to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to separate an egg yolk from the white.", type: "calibration" },
  { text: "Describe a chair without using the words \"sit,\" \"legs,\" or \"back.\"", type: "calibration" },
  { text: "Name as many zoo animals as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a group of people standing together, no context given]", type: "calibration" },
  { text: "Describe the taste of a cooked carrot to someone who has never had it.", type: "calibration" },
  { text: "Describe every object within arm's reach.", type: "calibration" },
  { text: "Describe the feel of a nylon windbreaker to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of lemon zest to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of footsteps on hardwood to someone who has never heard it.", type: "calibration" },
  { text: "Describe a key to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to boil an egg.", type: "calibration" },
  { text: "Describe a couch without using the words \"sit,\" \"soft,\" or \"cushion.\"", type: "calibration" },
  { text: "Name as many breeds of dog as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an empty room photographed from a doorway]", type: "calibration" },
  { text: "Describe the taste of celery to someone who has never had it.", type: "calibration" },
  { text: "Describe the sounds you can hear right now, near to far.", type: "calibration" },
  { text: "Describe the feel of leather to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of an orange being peeled to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of footsteps on carpet to someone who has never heard it.", type: "calibration" },
  { text: "Describe a padlock to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to poach an egg.", type: "calibration" },
  { text: "Describe a bed without using the words \"sleep,\" \"mattress,\" or \"soft.\"", type: "calibration" },
  { text: "Name as many breeds of cat as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a crowded sidewalk]", type: "calibration" },
  { text: "Describe the taste of a cucumber to someone who has never had it.", type: "calibration" },
  { text: "Describe the surface of the nearest table or desk.", type: "calibration" },
  { text: "Describe the feel of suede to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of cut grass to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of footsteps in snow to someone who has never heard it.", type: "calibration" },
  { text: "Describe a doorknob to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to scramble eggs.", type: "calibration" },
  { text: "Describe a pillow without using the words \"soft,\" \"head,\" or \"sleep.\"", type: "calibration" },
  { text: "Name as many kinds of bird as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an aerial view of farmland]", type: "calibration" },
  { text: "Describe the taste of iceberg lettuce to someone who has never had it.", type: "calibration" },
  { text: "Describe the ceiling above you in detail.", type: "calibration" },
  { text: "Describe the feel of patent leather to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of pine trees to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a zipper being zipped to someone who has never heard it.", type: "calibration" },
  { text: "Describe a hinge to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fry an egg sunny-side up.", type: "calibration" },
  { text: "Describe a blanket without using the words \"warm,\" \"soft,\" or \"bed.\"", type: "calibration" },
  { text: "Name as many kinds of fish as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a black-and-white photograph of unfamiliar architecture]", type: "calibration" },
  { text: "Describe the taste of spinach to someone who has never had it.", type: "calibration" },
  { text: "Describe the floor beneath you in detail.", type: "calibration" },
  { text: "Describe the feel of canvas to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a eucalyptus leaf crushed to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of velcro being pulled apart to someone who has never heard it.", type: "calibration" },
  { text: "Describe a light switch to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to make an omelet.", type: "calibration" },
  { text: "Describe a lamp without using the words \"light,\" \"bulb,\" or \"on.\"", type: "calibration" },
  { text: "Name as many insects as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a color photograph of a coastline]", type: "calibration" },
  { text: "Describe the taste of kale to someone who has never had it.", type: "calibration" },
  { text: "Describe the walls of the room you're in.", type: "calibration" },
  { text: "Describe the feel of burlap to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of lavender to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of paper being crumpled to someone who has never heard it.", type: "calibration" },
  { text: "Describe a power outlet to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to cook rice on a stovetop.", type: "calibration" },
  { text: "Describe a window without using the words \"glass,\" \"see,\" or \"open.\"", type: "calibration" },
  { text: "Name as many reptiles as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a photograph of a kitchen mid-meal-preparation]", type: "calibration" },
  { text: "Describe the taste of arugula to someone who has never had it.", type: "calibration" },
  { text: "Describe the doorway nearest to you.", type: "calibration" },
  { text: "Describe the feel of satin to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of fresh mint to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of paper being torn to someone who has never heard it.", type: "calibration" },
  { text: "Describe a plug to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to cook pasta.", type: "calibration" },
  { text: "Describe a door without using the words \"open,\" \"close,\" or \"wood.\"", type: "calibration" },
  { text: "Name as many amphibians as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a laundry line with clothes hanging]", type: "calibration" },
  { text: "Describe the taste of a bell pepper to someone who has never had it.", type: "calibration" },
  { text: "Describe the chair you're sitting in or standing near.", type: "calibration" },
  { text: "Describe the feel of a fresh bedsheet to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of cinnamon to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of scissors cutting paper to someone who has never heard it.", type: "calibration" },
  { text: "Describe an extension cord to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to drain pasta without losing any.", type: "calibration" },
  { text: "Describe a key without using the words \"metal,\" \"lock,\" or \"open.\"", type: "calibration" },
  { text: "Name as many sea creatures as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a window seen from outside at night]", type: "calibration" },
  { text: "Describe the taste of a raw onion to someone who has never had it.", type: "calibration" },
  { text: "Describe the lighting fixtures you can see.", type: "calibration" },
  { text: "Describe the feel of a line-dried towel to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of nutmeg to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a pencil being sharpened to someone who has never heard it.", type: "calibration" },
  { text: "Describe a flashlight to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to chop an onion.", type: "calibration" },
  { text: "Describe a clock without using the words \"time,\" \"hands,\" or \"tick.\"", type: "calibration" },
  { text: "Name as many extinct animals as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a window seen from inside looking out at day]", type: "calibration" },
  { text: "Describe the taste of a cooked onion to someone who has never had it.", type: "calibration" },
  { text: "Describe the largest object in the room.", type: "calibration" },
  { text: "Describe the feel of a machine-dried towel to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of vanilla to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of writing with a ballpoint pen to someone who has never heard it.", type: "calibration" },
  { text: "Describe a candle to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to mince garlic.", type: "calibration" },
  { text: "Describe a book without using the words \"read,\" \"pages,\" or \"words.\"", type: "calibration" },
  { text: "Name as many mythical creatures as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a storefront at night]", type: "calibration" },
  { text: "Describe the taste of a raw garlic clove to someone who has never had it.", type: "calibration" },
  { text: "Describe the smallest object you can see without moving.", type: "calibration" },
  { text: "Describe the feel of a wool blanket to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a Christmas tree to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of typing on a keyboard to someone who has never heard it.", type: "calibration" },
  { text: "Describe a match to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to peel a clove of garlic quickly.", type: "calibration" },
  { text: "Describe a pencil without using the words \"write,\" \"wood,\" or \"lead.\"", type: "calibration" },
  { text: "Name as many fruits as you can in 60 seconds.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a storefront during business hours]", type: "calibration" },
  { text: "Describe the taste of roasted garlic to someone who has never had it.", type: "calibration" },
  { text: "Describe what's on the nearest shelf.", type: "calibration" },
  { text: "Describe the feel of a weighted blanket to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a campfire to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a mechanical keyboard to someone who has never heard it.", type: "calibration" },
  { text: "Describe a lighter to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to peel a hard-boiled egg.", type: "calibration" },
  { text: "Describe a pen without using the words \"write,\" \"ink,\" or \"paper.\"", type: "calibration" },
  { text: "Name as many vegetables as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a piece of machinery in close-up]", type: "calibration" },
  { text: "Describe the taste of fresh basil to someone who has never had it.", type: "calibration" },
  { text: "Describe the wastebasket or trash can closest to you.", type: "calibration" },
  { text: "Describe the feel of a down comforter to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of woodsmoke from a distance to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a laptop fan to someone who has never heard it.", type: "calibration" },
  { text: "Describe a pencil to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to peel a potato.", type: "calibration" },
  { text: "Describe a notebook without using the words \"write,\" \"pages,\" or \"lines.\"", type: "calibration" },
  { text: "Name as many kinds of cheese as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a bicycle leaned against a wall]", type: "calibration" },
  { text: "Describe the taste of dried oregano to someone who has never had it.", type: "calibration" },
  { text: "Describe the kitchen you use most often, physically.", type: "calibration" },
  { text: "Describe the feel of smooth river stones to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a struck match to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a clock ticking to someone who has never heard it.", type: "calibration" },
  { text: "Describe a ballpoint pen to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to dice a potato.", type: "calibration" },
  { text: "Describe an envelope without using the words \"letter,\" \"mail,\" or \"open.\"", type: "calibration" },
  { text: "Name as many kinds of bread as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a parked car from the side]", type: "calibration" },
  { text: "Describe the taste of cinnamon to someone who has never had it.", type: "calibration" },
  { text: "Describe the bathroom you use most often, physically.", type: "calibration" },
  { text: "Describe the feel of coarse sand to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of candle wax to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of an alarm clock to someone who has never heard it.", type: "calibration" },
  { text: "Describe an eraser to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to slice a tomato thinly.", type: "calibration" },
  { text: "Describe a telephone without using the words \"call,\" \"talk,\" or \"ring.\"", type: "calibration" },
  { text: "Name as many kinds of pasta as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a pair of shoes on a floor]", type: "calibration" },
  { text: "Describe the taste of vanilla extract to someone who has never had it.", type: "calibration" },
  { text: "Describe the hallway of the place where you live.", type: "calibration" },
  { text: "Describe the feel of fine sand to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of an extinguished candle to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a microwave beeping to someone who has never heard it.", type: "calibration" },
  { text: "Describe a ruler to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to segment a grapefruit.", type: "calibration" },
  { text: "Describe a computer without using the words \"screen,\" \"type,\" or \"click.\"", type: "calibration" },
  { text: "Name as many kinds of rice dish as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an animal in its habitat]", type: "calibration" },
  { text: "Describe the taste of black pepper to someone who has never had it.", type: "calibration" },
  { text: "Describe the entryway of the place where you live.", type: "calibration" },
  { text: "Describe the feel of wet sand to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of petrichor after rain to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of a kettle whistling to someone who has never heard it.", type: "calibration" },
  { text: "Describe a notebook to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to juice a lemon without a juicer.", type: "calibration" },
  { text: "Describe a television without using the words \"watch,\" \"screen,\" or \"show.\"", type: "calibration" },
  { text: "Name as many kinds of soup as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a domestic pet indoors]", type: "calibration" },
  { text: "Describe the taste of table salt to someone who has never had it.", type: "calibration" },
  { text: "Describe the view from your front door looking out.", type: "calibration" },
  { text: "Describe the feel of dry beach grass to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of ocean air to someone who has never smelled it.", type: "calibration" },
  { text: "Describe the sound of water boiling to someone who has never heard it.", type: "calibration" },
  { text: "Describe a spiral-bound notebook to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to grate cheese by hand.", type: "calibration" },
  { text: "Describe a radio without using the words \"listen,\" \"music,\" or \"sound.\"", type: "calibration" },
  { text: "Name as many kinds of salad as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a handwritten note on paper]", type: "calibration" },
  { text: "Describe the taste of sea salt to someone who has never had it.", type: "calibration" },
  { text: "Describe the view from your front door looking in.", type: "calibration" },
  { text: "Describe the feel of moss on a rock to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a pine forest after rain to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a manila folder to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to knead bread dough.", type: "calibration" },
  { text: "Describe a guitar without using the words \"music,\" \"strings,\" or \"play.\"", type: "calibration" },
  { text: "Name as many kinds of sandwich as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a printed receipt on a table]", type: "calibration" },
  { text: "Describe the taste of sugar to someone who has never had it.", type: "calibration" },
  { text: "Describe a grocery store you know well, aisle by aisle.", type: "calibration" },
  { text: "Describe the feel of tree bark to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of wet asphalt in summer to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a three-ring binder to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to roll out pie crust.", type: "calibration" },
  { text: "Describe a drum without using the words \"hit,\" \"beat,\" or \"sound.\"", type: "calibration" },
  { text: "Name as many breakfast foods as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a pile of mail on a counter]", type: "calibration" },
  { text: "Describe the taste of honey to someone who has never had it.", type: "calibration" },
  { text: "Describe a coffee shop you know well.", type: "calibration" },
  { text: "Describe the feel of smooth birch bark to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of snow to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a sticky note to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to whip cream by hand.", type: "calibration" },
  { text: "Describe a piano without using the words \"keys,\" \"music,\" or \"play.\"", type: "calibration" },
  { text: "Name as many desserts as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a bookshelf from straight on]", type: "calibration" },
  { text: "Describe the taste of maple syrup to someone who has never had it.", type: "calibration" },
  { text: "Describe a park you know well in physical detail.", type: "calibration" },
  { text: "Describe the feel of pine needles to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of autumn leaves to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a highlighter to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to whisk egg whites to stiff peaks.", type: "calibration" },
  { text: "Describe a violin without using the words \"music,\" \"strings,\" or \"bow.\"", type: "calibration" },
  { text: "Name as many candies as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a refrigerator's interior]", type: "calibration" },
  { text: "Describe the taste of molasses to someone who has never had it.", type: "calibration" },
  { text: "Describe a street corner you pass often.", type: "calibration" },
  { text: "Describe the feel of an acorn to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of fresh laundry to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a pair of scissors to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to frost a cake.", type: "calibration" },
  { text: "Describe a basketball without using the words \"bounce,\" \"orange,\" or \"round.\"", type: "calibration" },
  { text: "Name as many kinds of cookie as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a pantry's interior]", type: "calibration" },
  { text: "Describe the taste of dark chocolate to someone who has never had it.", type: "calibration" },
  { text: "Describe a bus stop or subway stop you use often.", type: "calibration" },
  { text: "Describe the feel of a pinecone to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a line-dried sheet to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a tape dispenser to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fold a napkin into a triangle.", type: "calibration" },
  { text: "Describe a baseball without using the words \"throw,\" \"bat,\" or \"white.\"", type: "calibration" },
  { text: "Name as many kinds of cake as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a closet's interior]", type: "calibration" },
  { text: "Describe the taste of milk chocolate to someone who has never had it.", type: "calibration" },
  { text: "Describe the interior of a car you ride in often.", type: "calibration" },
  { text: "Describe the feel of a maple leaf to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of an old book to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a glue stick to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to set a formal dinner table.", type: "calibration" },
  { text: "Describe a football without using the words \"throw,\" \"kick,\" or \"brown.\"", type: "calibration" },
  { text: "Name as many ice cream flavors as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a bathroom vanity top]", type: "calibration" },
  { text: "Describe the taste of white chocolate to someone who has never had it.", type: "calibration" },
  { text: "Describe a parking lot you use often.", type: "calibration" },
  { text: "Describe the feel of a dry oak leaf to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a new book to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a calculator to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fold a fitted sheet.", type: "calibration" },
  { text: "Describe a tennis racket without using the words \"hit,\" \"ball,\" or \"strings.\"", type: "calibration" },
  { text: "Name as many spices as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a nightstand with objects on it]", type: "calibration" },
  { text: "Describe the taste of unsweetened cocoa powder to someone who has never had it.", type: "calibration" },
  { text: "Describe an elevator you've used recently.", type: "calibration" },
  { text: "Describe the feel of a wet autumn leaf to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a leather-bound journal to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a rubber stamp to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to make a bed with hospital corners.", type: "calibration" },
  { text: "Describe a bicycle without using the words \"ride,\" \"wheels,\" or \"pedal.\"", type: "calibration" },
  { text: "Name as many herbs as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a child's toys on the floor]", type: "calibration" },
  { text: "Describe the taste of a fresh strawberry to someone who has never had it.", type: "calibration" },
  { text: "Describe a staircase you climb often.", type: "calibration" },
  { text: "Describe the feel of grass underfoot to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a bookstore to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a magnifying glass to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fold a T-shirt.", type: "calibration" },
  { text: "Describe a skateboard without using the words \"ride,\" \"wheels,\" or \"roll.\"", type: "calibration" },
  { text: "Name as many beverages as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a garden bed in mid-growing-season]", type: "calibration" },
  { text: "Describe the taste of a raspberry to someone who has never had it.", type: "calibration" },
  { text: "Describe a bookstore you remember well.", type: "calibration" },
  { text: "Describe the feel of clover to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a library to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a compass to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fold a dress shirt for packing.", type: "calibration" },
  { text: "Describe a car without using the words \"drive,\" \"wheels,\" or \"road.\"", type: "calibration" },
  { text: "Name as many non-alcoholic drinks as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a tree in autumn]", type: "calibration" },
  { text: "Describe the taste of a blueberry to someone who has never had it.", type: "calibration" },
  { text: "Describe a library you've spent time in.", type: "calibration" },
  { text: "Describe the feel of a dandelion puff to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of printer toner to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a protractor to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to iron a dress shirt.", type: "calibration" },
  { text: "Describe a train without using the words \"tracks,\" \"move,\" or \"cars.\"", type: "calibration" },
  { text: "Name as many teas as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a tree in winter]", type: "calibration" },
  { text: "Describe the taste of a blackberry to someone who has never had it.", type: "calibration" },
  { text: "Describe a school hallway from your memory.", type: "calibration" },
  { text: "Describe the feel of a cactus spine to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of pencil shavings to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a slide rule to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to sew a button back onto a shirt.", type: "calibration" },
  { text: "Describe an airplane without using the words \"fly,\" \"wings,\" or \"sky.\"", type: "calibration" },
  { text: "Name as many coffee drinks as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a tree in spring]", type: "calibration" },
  { text: "Describe the taste of a fresh peach to someone who has never had it.", type: "calibration" },
  { text: "Describe a classroom from your memory.", type: "calibration" },
  { text: "Describe the feel of aloe vera gel to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of a permanent marker to someone who has never smelled it.", type: "calibration" },
  { text: "Describe an abacus to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to thread a needle.", type: "calibration" },
  { text: "Describe a boat without using the words \"water,\" \"float,\" or \"sail.\"", type: "calibration" },
  { text: "Name as many kinds of nut as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a field of tall grass]", type: "calibration" },
  { text: "Describe the taste of a plum to someone who has never had it.", type: "calibration" },
  { text: "Describe a gymnasium from your memory.", type: "calibration" },
  { text: "Describe the feel of raw bread dough to someone who has never felt it.", type: "calibration" },
  { text: "Describe the smell of rubber cement to someone who has never smelled it.", type: "calibration" },
  { text: "Describe a fork to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tie off a thread after sewing.", type: "calibration" },
  { text: "Describe a shoe without using the words \"foot,\" \"walk,\" or \"lace.\"", type: "calibration" },
  { text: "Name as many kinds of berry as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a beach at low tide]", type: "calibration" },
  { text: "Describe the taste of a nectarine to someone who has never had it.", type: "calibration" },
  { text: "Describe a cafeteria from your memory.", type: "calibration" },
  { text: "Describe a spoon to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to mend a small tear in fabric.", type: "calibration" },
  { text: "Describe a sock without using the words \"foot,\" \"cotton,\" or \"warm.\"", type: "calibration" },
  { text: "Name as many tropical fruits as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a beach at high tide]", type: "calibration" },
  { text: "Describe the taste of a fresh apricot to someone who has never had it.", type: "calibration" },
  { text: "Describe an office lobby you've waited in.", type: "calibration" },
  { text: "Describe a butter knife to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to remove a wine stain from a tablecloth.", type: "calibration" },
  { text: "Describe a hat without using the words \"head,\" \"wear,\" or \"cover.\"", type: "calibration" },
  { text: "Name as many root vegetables as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a mountain ridge in clear weather]", type: "calibration" },
  { text: "Describe the taste of a dried apricot to someone who has never had it.", type: "calibration" },
  { text: "Describe a waiting room at a doctor's office.", type: "calibration" },
  { text: "Describe a steak knife to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to wash a wool sweater by hand.", type: "calibration" },
  { text: "Describe a coat without using the words \"wear,\" \"warm,\" or \"winter.\"", type: "calibration" },
  { text: "Name as many leafy greens as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a foggy forest floor]", type: "calibration" },
  { text: "Describe the taste of a prune to someone who has never had it.", type: "calibration" },
  { text: "Describe a hotel room you've stayed in.", type: "calibration" },
  { text: "Describe chopsticks to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to polish a pair of leather shoes.", type: "calibration" },
  { text: "Describe a pair of jeans without using the words \"pants,\" \"blue,\" or \"denim.\"", type: "calibration" },
  { text: "Name as many cuts of meat as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a riverbank with rocks]", type: "calibration" },
  { text: "Describe the taste of a raisin to someone who has never had it.", type: "calibration" },
  { text: "Describe an airport terminal you've passed through.", type: "calibration" },
  { text: "Describe a dinner plate to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to shine silverware.", type: "calibration" },
  { text: "Describe a belt without using the words \"waist,\" \"pants,\" or \"hold.\"", type: "calibration" },
  { text: "Name as many colors as you can in 60 seconds.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a waterfall from a distance]", type: "calibration" },
  { text: "Describe the taste of a fresh fig to someone who has never had it.", type: "calibration" },
  { text: "Describe a gas station you've been to.", type: "calibration" },
  { text: "Describe a bowl to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to clean a cast iron pan.", type: "calibration" },
  { text: "Describe a necklace without using the words \"wear,\" \"neck,\" or \"chain.\"", type: "calibration" },
  { text: "Name as many shades of red as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a snowy street]", type: "calibration" },
  { text: "Describe the taste of a dried fig to someone who has never had it.", type: "calibration" },
  { text: "Describe a diner you remember.", type: "calibration" },
  { text: "Describe a mug to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to season a cast iron pan.", type: "calibration" },
  { text: "Describe a ring without using the words \"finger,\" \"wear,\" or \"round.\"", type: "calibration" },
  { text: "Name as many shades of blue as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a rainy sidewalk]", type: "calibration" },
  { text: "Describe the taste of a date to someone who has never had it.", type: "calibration" },
  { text: "Describe a place of worship you've seen inside.", type: "calibration" },
  { text: "Describe a wine glass to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to sharpen a kitchen knife.", type: "calibration" },
  { text: "Describe a pair of glasses without using the words \"see,\" \"eyes,\" or \"frame.\"", type: "calibration" },
  { text: "Name as many shades of green as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a sunset over water]", type: "calibration" },
  { text: "Describe the taste of a pomegranate seed to someone who has never had it.", type: "calibration" },
  { text: "Describe a stadium or arena you've been inside.", type: "calibration" },
  { text: "Describe a pint glass to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to sharpen a pencil with a pocketknife.", type: "calibration" },
  { text: "Describe a watch without using the words \"time,\" \"wrist,\" or \"face.\"", type: "calibration" },
  { text: "Name as many shades of brown as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a sunrise through trees]", type: "calibration" },
  { text: "Describe the taste of a grapefruit to someone who has never had it.", type: "calibration" },
  { text: "Describe a theater you've attended.", type: "calibration" },
  { text: "Describe a teapot to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to unclog a kitchen sink.", type: "calibration" },
  { text: "Describe a banana without using the words \"yellow,\" \"fruit,\" or \"peel.\"", type: "calibration" },
  { text: "Name as many countries as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a parking lot from above]", type: "calibration" },
  { text: "Describe the taste of a lemon to someone who has never had it.", type: "calibration" },
  { text: "Describe a museum gallery you've walked through.", type: "calibration" },
  { text: "Describe a kettle to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to plunge a toilet.", type: "calibration" },
  { text: "Describe an apple without using the words \"red,\" \"fruit,\" or \"tree.\"", type: "calibration" },
  { text: "Name as many capital cities as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a gas station forecourt]", type: "calibration" },
  { text: "Describe the taste of a lime to someone who has never had it.", type: "calibration" },
  { text: "Describe a beach you've visited, physically.", type: "calibration" },
  { text: "Describe a frying pan to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to replace a light bulb in a ceiling fixture.", type: "calibration" },
  { text: "Describe an orange without using the words \"orange,\" \"fruit,\" or \"juice.\"", type: "calibration" },
  { text: "Name as many U.S. states as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a diner interior]", type: "calibration" },
  { text: "Describe the taste of an orange to someone who has never had it.", type: "calibration" },
  { text: "Describe a forest path you've walked.", type: "calibration" },
  { text: "Describe a saucepan to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to change the batteries in a smoke detector.", type: "calibration" },
  { text: "Describe a strawberry without using the words \"red,\" \"fruit,\" or \"seed.\"", type: "calibration" },
  { text: "Name as many European countries as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a coffee shop counter]", type: "calibration" },
  { text: "Describe the taste of a tangerine to someone who has never had it.", type: "calibration" },
  { text: "Describe a riverbank you've stood on.", type: "calibration" },
  { text: "Describe a colander to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to reset a tripped circuit breaker.", type: "calibration" },
  { text: "Describe a grape without using the words \"small,\" \"round,\" or \"wine.\"", type: "calibration" },
  { text: "Name as many Asian countries as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a library reading room]", type: "calibration" },
  { text: "Describe the taste of a kiwi to someone who has never had it.", type: "calibration" },
  { text: "Describe a bridge you've crossed on foot.", type: "calibration" },
  { text: "Describe a grater to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to use a tape measure accurately.", type: "calibration" },
  { text: "Describe a watermelon without using the words \"red,\" \"green,\" or \"seed.\"", type: "calibration" },
  { text: "Name as many African countries as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a bookstore aisle]", type: "calibration" },
  { text: "Describe the taste of a mango to someone who has never had it.", type: "calibration" },
  { text: "Describe the inside of a barn.", type: "calibration" },
  { text: "Describe a whisk to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to read a ruler down to the sixteenth of an inch.", type: "calibration" },
  { text: "Describe a pineapple without using the words \"yellow,\" \"sweet,\" or \"tropical.\"", type: "calibration" },
  { text: "Name as many South American countries as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a train station platform]", type: "calibration" },
  { text: "Describe the taste of a papaya to someone who has never had it.", type: "calibration" },
  { text: "Describe a farmer's market you've been to.", type: "calibration" },
  { text: "Describe a spatula to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to hang a picture level.", type: "calibration" },
  { text: "Describe a coconut without using the words \"brown,\" \"tropical,\" or \"shell.\"", type: "calibration" },
  { text: "Name as many island nations as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a subway car interior]", type: "calibration" },
  { text: "Describe the taste of a pineapple to someone who has never had it.", type: "calibration" },
  { text: "Describe a city square at midday.", type: "calibration" },
  { text: "Describe a ladle to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to drive a nail without bending it.", type: "calibration" },
  { text: "Describe a carrot without using the words \"orange,\" \"vegetable,\" or \"crunch.\"", type: "calibration" },
  { text: "Name as many rivers as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a bus stop shelter]", type: "calibration" },
  { text: "Describe the taste of a watermelon to someone who has never had it.", type: "calibration" },
  { text: "Describe an alley between two buildings.", type: "calibration" },
  { text: "Describe a rolling pin to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to use a screwdriver without stripping the screw.", type: "calibration" },
  { text: "Describe a potato without using the words \"brown,\" \"cook,\" or \"starch.\"", type: "calibration" },
  { text: "Name as many mountain ranges as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an airport gate seating area]", type: "calibration" },
  { text: "Describe the taste of a cantaloupe to someone who has never had it.", type: "calibration" },
  { text: "Describe a rooftop view you've seen.", type: "calibration" },
  { text: "Describe a can opener to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to use a hand saw.", type: "calibration" },
  { text: "Describe a tomato without using the words \"red,\" \"round,\" or \"sauce.\"", type: "calibration" },
  { text: "Name as many deserts as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a hospital hallway]", type: "calibration" },
  { text: "Describe the taste of a honeydew to someone who has never had it.", type: "calibration" },
  { text: "Describe a corkscrew to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to drill a hole in wood.", type: "calibration" },
  { text: "Describe a cucumber without using the words \"green,\" \"long,\" or \"cool.\"", type: "calibration" },
  { text: "Name as many oceans and seas as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a school hallway between classes]", type: "calibration" },
  { text: "Describe the taste of an avocado to someone who has never had it.", type: "calibration" },
  { text: "Describe a bottle opener to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to use a level.", type: "calibration" },
  { text: "Describe a lettuce leaf without using the words \"green,\" \"salad,\" or \"leaf.\"", type: "calibration" },
  { text: "Name as many lakes as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an empty classroom]", type: "calibration" },
  { text: "Describe the taste of a tomato to someone who has never had it.", type: "calibration" },
  { text: "Describe a garlic press to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to paint a wall without leaving roller marks.", type: "calibration" },
  { text: "Describe an onion without using the words \"layer,\" \"cry,\" or \"smell.\"", type: "calibration" },
  { text: "Name as many languages as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a cluttered garage]", type: "calibration" },
  { text: "Describe the taste of olive oil to someone who has never had it.", type: "calibration" },
  { text: "Describe a peeler to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to cut in paint along a ceiling line.", type: "calibration" },
  { text: "Describe a loaf of bread without using the words \"bake,\" \"slice,\" or \"wheat.\"", type: "calibration" },
  { text: "Name as many sports as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an attic interior]", type: "calibration" },
  { text: "Describe the taste of butter to someone who has never had it.", type: "calibration" },
  { text: "Describe a toaster to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to remove wallpaper.", type: "calibration" },
  { text: "Describe a bagel without using the words \"round,\" \"hole,\" or \"bread.\"", type: "calibration" },
  { text: "Name as many Olympic events as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a basement interior]", type: "calibration" },
  { text: "Describe a microwave to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to patch a small hole in drywall.", type: "calibration" },
  { text: "Describe a pizza without using the words \"cheese,\" \"slice,\" or \"round.\"", type: "calibration" },
  { text: "Name as many team sports as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a laundry room]", type: "calibration" },
  { text: "Describe a blender to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to caulk a bathtub.", type: "calibration" },
  { text: "Describe a hamburger without using the words \"meat,\" \"bun,\" or \"grill.\"", type: "calibration" },
  { text: "Name as many individual sports as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a kitchen from a low angle]", type: "calibration" },
  { text: "Describe a coffee maker to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to replace a faucet washer.", type: "calibration" },
  { text: "Describe a hot dog without using the words \"bun,\" \"meat,\" or \"mustard.\"", type: "calibration" },
  { text: "Name as many martial arts as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a living room from a high angle]", type: "calibration" },
  { text: "Describe a refrigerator to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to plant a seed in a pot.", type: "calibration" },
  { text: "Describe a taco without using the words \"shell,\" \"meat,\" or \"fold.\"", type: "calibration" },
  { text: "Name as many dance styles as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a bedroom from the doorway]", type: "calibration" },
  { text: "Describe a washing machine to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to transplant a houseplant.", type: "calibration" },
  { text: "Describe spaghetti without using the words \"pasta,\" \"sauce,\" or \"noodle.\"", type: "calibration" },
  { text: "Name as many musical instruments as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a hallway with several doors]", type: "calibration" },
  { text: "Describe a clothes iron to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to prune a rose bush.", type: "calibration" },
  { text: "Describe a waffle without using the words \"breakfast,\" \"syrup,\" or \"square.\"", type: "calibration" },
  { text: "Name as many stringed instruments as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a staircase going up]", type: "calibration" },
  { text: "Describe a vacuum cleaner to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to mow a lawn in neat stripes.", type: "calibration" },
  { text: "Describe a pancake without using the words \"breakfast,\" \"syrup,\" or \"round.\"", type: "calibration" },
  { text: "Name as many wind instruments as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a staircase going down]", type: "calibration" },
  { text: "Describe a broom to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to rake leaves into a pile and bag them.", type: "calibration" },
  { text: "Describe an omelet without using the words \"egg,\" \"fold,\" or \"breakfast.\"", type: "calibration" },
  { text: "Name as many percussion instruments as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an elevator interior]", type: "calibration" },
  { text: "Describe a dustpan to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to shovel snow from a driveway.", type: "calibration" },
  { text: "Describe a donut without using the words \"round,\" \"hole,\" or \"sweet.\"", type: "calibration" },
  { text: "Name as many musical genres as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a bank of mailboxes]", type: "calibration" },
  { text: "Describe a mop to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to check the oil in a car.", type: "calibration" },
  { text: "Describe a cupcake without using the words \"cake,\" \"small,\" or \"frosting.\"", type: "calibration" },
  { text: "Name as many board games as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a small boat tied at a dock]", type: "calibration" },
  { text: "Describe a sponge to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to change a flat tire.", type: "calibration" },
  { text: "Describe ice cream without using the words \"cold,\" \"sweet,\" or \"cream.\"", type: "calibration" },
  { text: "Name as many card games as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a ship at a commercial port]", type: "calibration" },
  { text: "Describe a dish rack to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to jump-start a car with cables.", type: "calibration" },
  { text: "Describe a popsicle without using the words \"cold,\" \"stick,\" or \"frozen.\"", type: "calibration" },
  { text: "Name as many video game genres as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a fishing pier]", type: "calibration" },
  { text: "Describe a paper towel roll to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to parallel park between two cars.", type: "calibration" },
  { text: "Describe a candy bar without using the words \"sweet,\" \"wrapper,\" or \"bar.\"", type: "calibration" },
  { text: "Name as many classic arcade games as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a lighthouse at a distance]", type: "calibration" },
  { text: "Describe a roll of toilet paper to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to merge onto a highway.", type: "calibration" },
  { text: "Describe a lollipop without using the words \"stick,\" \"sweet,\" or \"suck.\"", type: "calibration" },
  { text: "Name as many tools in a toolbox as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a bridge over water]", type: "calibration" },
  { text: "Describe a toothbrush to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to use a manual transmission to start from a stop.", type: "calibration" },
  { text: "Describe a cloud without using the words \"sky,\" \"white,\" or \"float.\"", type: "calibration" },
  { text: "Name as many kitchen utensils as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a tunnel entrance]", type: "calibration" },
  { text: "Describe a tube of toothpaste to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to ride a bicycle to a total beginner.", type: "calibration" },
  { text: "Describe rain without using the words \"water,\" \"drop,\" or \"wet.\"", type: "calibration" },
  { text: "Name as many items found in a bathroom as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a highway at night with motion blur]", type: "calibration" },
  { text: "Describe a bar of soap to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to balance on a bicycle without pedaling.", type: "calibration" },
  { text: "Describe snow without using the words \"white,\" \"cold,\" or \"fall.\"", type: "calibration" },
  { text: "Name as many items found in a kitchen as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a country road without cars]", type: "calibration" },
  { text: "Describe a shampoo bottle to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to shift gears on a multi-speed bicycle.", type: "calibration" },
  { text: "Describe a rainbow without using the words \"color,\" \"arc,\" or \"sky.\"", type: "calibration" },
  { text: "Name as many items found in an office as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a suburban driveway]", type: "calibration" },
  { text: "Describe a razor to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to pump air into a bicycle tire.", type: "calibration" },
  { text: "Describe the wind without using the words \"blow,\" \"air,\" or \"move.\"", type: "calibration" },
  { text: "Name as many items found in a garage as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a neighborhood from a hill]", type: "calibration" },
  { text: "Describe a hair dryer to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to patch a bicycle inner tube.", type: "calibration" },
  { text: "Describe the moon without using the words \"round,\" \"night,\" or \"sky.\"", type: "calibration" },
  { text: "Name as many items found in a garden shed as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a city skyline from far away]", type: "calibration" },
  { text: "Describe a comb to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to put a chain back onto a bike.", type: "calibration" },
  { text: "Describe the sun without using the words \"hot,\" \"yellow,\" or \"sky.\"", type: "calibration" },
  { text: "Name as many items found in a first aid kit as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a single skyscraper from street level]", type: "calibration" },
  { text: "Describe a hairbrush to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to lock a bike securely to a rack.", type: "calibration" },
  { text: "Describe a star without using the words \"sky,\" \"twinkle,\" or \"far.\"", type: "calibration" },
  { text: "Name as many items in a desk drawer as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a construction site]", type: "calibration" },
  { text: "Describe a pair of tweezers to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to swim freestyle.", type: "calibration" },
  { text: "Describe a tree without using the words \"leaves,\" \"branch,\" or \"green.\"", type: "calibration" },
  { text: "Name as many things you can find in a supermarket as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a road crew at work]", type: "calibration" },
  { text: "Describe a nail clipper to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tread water.", type: "calibration" },
  { text: "Describe a flower without using the words \"pretty,\" \"color,\" or \"bloom.\"", type: "calibration" },
  { text: "Name as many things you can buy at a hardware store as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an open-air market]", type: "calibration" },
  { text: "Describe a cotton swab to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to float on your back.", type: "calibration" },
  { text: "Describe grass without using the words \"green,\" \"mow,\" or \"lawn.\"", type: "calibration" },
  { text: "Name as many articles of clothing as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a covered market hall]", type: "calibration" },
  { text: "Describe a bandage to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to dive into a pool.", type: "calibration" },
  { text: "Describe a river without using the words \"water,\" \"flow,\" or \"bank.\"", type: "calibration" },
  { text: "Name as many types of shoe as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a bakery display case]", type: "calibration" },
  { text: "Describe a thermometer to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to throw a baseball.", type: "calibration" },
  { text: "Describe a mountain without using the words \"tall,\" \"rock,\" or \"peak.\"", type: "calibration" },
  { text: "Name as many types of hat as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a butcher shop counter]", type: "calibration" },
  { text: "Describe a pill bottle to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to swing a baseball bat.", type: "calibration" },
  { text: "Describe a beach without using the words \"sand,\" \"water,\" or \"wave.\"", type: "calibration" },
  { text: "Name as many types of coat as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a fish counter at a market]", type: "calibration" },
  { text: "Describe a syringe to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to catch a ball with a glove.", type: "calibration" },
  { text: "Describe an ocean without using the words \"water,\" \"blue,\" or \"wave.\"", type: "calibration" },
  { text: "Name as many fabrics as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a florist shop interior]", type: "calibration" },
  { text: "Describe a wristwatch to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to throw a frisbee in a straight line.", type: "calibration" },
  { text: "Describe a desert without using the words \"sand,\" \"hot,\" or \"dry.\"", type: "calibration" },
  { text: "Name as many jewelry items as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a hardware store aisle]", type: "calibration" },
  { text: "Describe a pocket watch to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to skip a stone on water.", type: "calibration" },
  { text: "Describe a forest without using the words \"tree,\" \"green,\" or \"wood.\"", type: "calibration" },
  { text: "Name as many body parts as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a greenhouse interior]", type: "calibration" },
  { text: "Describe a grandfather clock to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to shuffle a deck of cards.", type: "calibration" },
  { text: "Describe a dog without using the words \"pet,\" \"bark,\" or \"tail.\"", type: "calibration" },
  { text: "Name as many bones in the body as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a vegetable garden mid-summer]", type: "calibration" },
  { text: "Describe a digital alarm clock to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to deal cards for a game of poker.", type: "calibration" },
  { text: "Describe a cat without using the words \"pet,\" \"purr,\" or \"fur.\"", type: "calibration" },
  { text: "Name as many organs as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a chicken coop with chickens]", type: "calibration" },
  { text: "Describe a sundial to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to play rock-paper-scissors.", type: "calibration" },
  { text: "Describe a horse without using the words \"ride,\" \"tail,\" or \"mane.\"", type: "calibration" },
  { text: "Name as many muscles as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a horse in a stable]", type: "calibration" },
  { text: "Describe an hourglass to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to play tic-tac-toe and never lose.", type: "calibration" },
  { text: "Describe a fish without using the words \"water,\" \"swim,\" or \"scale.\"", type: "calibration" },
  { text: "Name as many parts of the face as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a cow in a pasture]", type: "calibration" },
  { text: "Describe a metronome to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fold a paper airplane that flies straight.", type: "calibration" },
  { text: "Describe a bird without using the words \"fly,\" \"wing,\" or \"sing.\"", type: "calibration" },
  { text: "Name as many parts of the hand as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a flock of sheep]", type: "calibration" },
  { text: "Describe a tuning fork to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fold an origami crane.", type: "calibration" },
  { text: "Describe a bee without using the words \"sting,\" \"honey,\" or \"buzz.\"", type: "calibration" },
  { text: "Name as many types of vehicle as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a dog on a leash]", type: "calibration" },
  { text: "Describe a harmonica to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fold an origami box.", type: "calibration" },
  { text: "Describe a spider without using the words \"web,\" \"leg,\" or \"crawl.\"", type: "calibration" },
  { text: "Name as many parts of a car as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a cat on a windowsill]", type: "calibration" },
  { text: "Describe a kazoo to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to wrap a rectangular gift with wrapping paper.", type: "calibration" },
  { text: "Describe an ant without using the words \"small,\" \"crawl,\" or \"hill.\"", type: "calibration" },
  { text: "Name as many parts of a bicycle as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a fishbowl on a counter]", type: "calibration" },
  { text: "Describe a tambourine to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to curl a ribbon with scissors.", type: "calibration" },
  { text: "Describe a butterfly without using the words \"fly,\" \"wing,\" or \"color.\"", type: "calibration" },
  { text: "Name as many parts of a house as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a bird feeder with birds]", type: "calibration" },
  { text: "Describe a triangle instrument to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to address an envelope for mailing.", type: "calibration" },
  { text: "Describe a mosquito without using the words \"bite,\" \"buzz,\" or \"itch.\"", type: "calibration" },
  { text: "Name as many rooms in a house as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an art studio mid-work]", type: "calibration" },
  { text: "Describe a cowbell to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fold a letter into thirds for a business envelope.", type: "calibration" },
  { text: "Describe a refrigerator without using the words \"cold,\" \"food,\" or \"door.\"", type: "calibration" },
  { text: "Name as many types of window as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a sculptor's workshop]", type: "calibration" },
  { text: "Describe a xylophone to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to seal an envelope without licking it.", type: "calibration" },
  { text: "Describe a stove without using the words \"cook,\" \"heat,\" or \"burner.\"", type: "calibration" },
  { text: "Name as many types of door as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a carpenter's workshop]", type: "calibration" },
  { text: "Describe a piano key to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tie a fishing hook onto a line.", type: "calibration" },
  { text: "Describe a microwave without using the words \"heat,\" \"minute,\" or \"beep.\"", type: "calibration" },
  { text: "Name as many types of flooring as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a mechanic's garage bay]", type: "calibration" },
  { text: "Describe a guitar pick to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to cast a fishing line.", type: "calibration" },
  { text: "Describe a toaster without using the words \"bread,\" \"heat,\" or \"pop.\"", type: "calibration" },
  { text: "Name as many types of roofing as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an empty auditorium]", type: "calibration" },
  { text: "Describe a violin bow to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to reel in a fish without losing it.", type: "calibration" },
  { text: "Describe a kettle without using the words \"water,\" \"hot,\" or \"whistle.\"", type: "calibration" },
  { text: "Name as many trees as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with an audience in silhouette]", type: "calibration" },
  { text: "Describe a drumstick to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to clean a whole fish.", type: "calibration" },
  { text: "Describe a blender without using the words \"mix,\" \"blade,\" or \"spin.\"", type: "calibration" },
  { text: "Name as many flowers as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a stage set between acts]", type: "calibration" },
  { text: "Describe a saxophone reed to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to set up a camping tent.", type: "calibration" },
  { text: "Describe a vacuum cleaner without using the words \"suck,\" \"dirt,\" or \"floor.\"", type: "calibration" },
  { text: "Name as many garden plants as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a musician's hands on an instrument without a face visible]", type: "calibration" },
  { text: "Describe a trumpet mute to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to build a small campfire.", type: "calibration" },
  { text: "Describe a washing machine without using the words \"wash,\" \"clothes,\" or \"spin.\"", type: "calibration" },
  { text: "Name as many houseplants as you can.", type: "calibration" },
  { text: "Describe what you see in this image: [pair with a sports field before a game]", type: "calibration" },
  { text: "Describe a bicycle chain to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to light a campfire without lighter fluid.", type: "calibration" },
  { text: "Describe an alarm clock without using the words \"time,\" \"ring,\" or \"wake.\"", type: "calibration" },
  { text: "Name as many gardening tools as you can.", type: "calibration" },
  { text: "Describe a bicycle pedal to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to roast a marshmallow without burning it.", type: "calibration" },
  { text: "Describe a mirror without using the words \"see,\" \"reflect,\" or \"glass.\"", type: "calibration" },
  { text: "Name as many weather phenomena as you can.", type: "calibration" },
  { text: "Describe a bike seat to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to set up a sleeping bag inside a tent.", type: "calibration" },
  { text: "Describe a camera without using the words \"picture,\" \"click,\" or \"lens.\"", type: "calibration" },
  { text: "Name as many constellations as you can.", type: "calibration" },
  { text: "Describe a kickstand to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to read a paper map to find a road.", type: "calibration" },
  { text: "Describe a flashlight without using the words \"light,\" \"battery,\" or \"dark.\"", type: "calibration" },
  { text: "Name as many planets and moons as you can.", type: "calibration" },
  { text: "Describe a bell on a bike to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to use a compass to find north.", type: "calibration" },
  { text: "Describe a candle without using the words \"wax,\" \"light,\" or \"flame.\"", type: "calibration" },
  { text: "Name as many chemical elements as you can.", type: "calibration" },
  { text: "Describe a car steering wheel to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tell time from the position of the sun.", type: "calibration" },
  { text: "Describe a broom without using the words \"sweep,\" \"floor,\" or \"dust.\"", type: "calibration" },
  { text: "Name as many minerals or rocks as you can.", type: "calibration" },
  { text: "Describe a turn signal lever to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to brush your teeth thoroughly.", type: "calibration" },
  { text: "Describe a bucket without using the words \"water,\" \"carry,\" or \"hold.\"", type: "calibration" },
  { text: "Name as many gemstones as you can.", type: "calibration" },
  { text: "Describe a rearview mirror to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to floss properly.", type: "calibration" },
  { text: "Describe a ladder without using the words \"climb,\" \"step,\" or \"up.\"", type: "calibration" },
  { text: "Name as many units of measurement as you can.", type: "calibration" },
  { text: "Describe a seatbelt to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to shave with a safety razor.", type: "calibration" },
  { text: "Describe a wheelchair without using the words \"wheel,\" \"sit,\" or \"move.\"", type: "calibration" },
  { text: "Name as many mathematical shapes as you can.", type: "calibration" },
  { text: "Describe a gear shift to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to trim your own fingernails.", type: "calibration" },
  { text: "Describe a stroller without using the words \"baby,\" \"push,\" or \"wheel.\"", type: "calibration" },
  { text: "Name as many mathematical operations as you can.", type: "calibration" },
  { text: "Describe a license plate to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to apply a bandage to a fingertip.", type: "calibration" },
  { text: "Describe a suitcase without using the words \"pack,\" \"travel,\" or \"zip.\"", type: "calibration" },
  { text: "Name as many mathematical constants as you can.", type: "calibration" },
  { text: "Describe a hubcap to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to take a pulse at the wrist.", type: "calibration" },
  { text: "Describe an umbrella without using the words \"rain,\" \"open,\" or \"cover.\"", type: "calibration" },
  { text: "Name as many punctuation marks as you can.", type: "calibration" },
  { text: "Describe a tire tread to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to measure a fever with a thermometer.", type: "calibration" },
  { text: "Describe a tent without using the words \"camp,\" \"pole,\" or \"cover.\"", type: "calibration" },
  { text: "Name as many parts of speech as you can.", type: "calibration" },
  { text: "Describe a car key fob to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to pack a suitcase efficiently.", type: "calibration" },
  { text: "Describe a sleeping bag without using the words \"sleep,\" \"warm,\" or \"zip.\"", type: "calibration" },
  { text: "Name as many words that start with the letter S as you can.", type: "calibration" },
  { text: "Describe a gas pump nozzle to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to roll clothes to save space in a bag.", type: "calibration" },
  { text: "Describe a backpack without using the words \"carry,\" \"strap,\" or \"school.\"", type: "calibration" },
  { text: "Name as many words that start with the letter B as you can.", type: "calibration" },
  { text: "Describe a traffic cone to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to check in at an airport kiosk.", type: "calibration" },
  { text: "Describe an elevator without using the words \"up,\" \"down,\" or \"button.\"", type: "calibration" },
  { text: "Name as many words that start with the letter M as you can.", type: "calibration" },
  { text: "Describe a manhole cover to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to go through airport security.", type: "calibration" },
  { text: "Describe an escalator without using the words \"step,\" \"move,\" or \"up.\"", type: "calibration" },
  { text: "Name as many words that start with the letter P as you can.", type: "calibration" },
  { text: "Describe a fire hydrant to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to find your gate in an unfamiliar airport.", type: "calibration" },
  { text: "Describe a staircase without using the words \"step,\" \"up,\" or \"climb.\"", type: "calibration" },
  { text: "Name as many words that start with the letter T as you can.", type: "calibration" },
  { text: "Describe a parking meter to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to ride a subway in a city you don't know.", type: "calibration" },
  { text: "Describe a fire hydrant without using the words \"water,\" \"red,\" or \"fire.\"", type: "calibration" },
  { text: "Name as many words that rhyme with 'light' as you can.", type: "calibration" },
  { text: "Describe a street sign to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to hail a cab in a crowded city.", type: "calibration" },
  { text: "Describe a stop sign without using the words \"stop,\" \"red,\" or \"eight.\"", type: "calibration" },
  { text: "Name as many words that rhyme with 'day' as you can.", type: "calibration" },
  { text: "Describe a mailbox to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tip at a restaurant.", type: "calibration" },
  { text: "Describe a traffic light without using the words \"red,\" \"green,\" or \"stop.\"", type: "calibration" },
  { text: "Name as many words that rhyme with 'run' as you can.", type: "calibration" },
  { text: "Describe a letter stamp to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to split a restaurant bill fairly.", type: "calibration" },
  { text: "Describe a parking meter without using the words \"coin,\" \"time,\" or \"park.\"", type: "calibration" },
  { text: "Name as many compound words as you can.", type: "calibration" },
  { text: "Describe an envelope to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to write a check.", type: "calibration" },
  { text: "Describe a bridge without using the words \"cross,\" \"over,\" or \"river.\"", type: "calibration" },
  { text: "Name as many adjectives for size as you can.", type: "calibration" },
  { text: "Describe a postcard to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to endorse a check for deposit.", type: "calibration" },
  { text: "Describe a tunnel without using the words \"dark,\" \"through,\" or \"long.\"", type: "calibration" },
  { text: "Name as many adjectives for speed as you can.", type: "calibration" },
  { text: "Describe a wax seal to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to balance a checkbook.", type: "calibration" },
  { text: "Describe a subway without using the words \"underground,\" \"train,\" or \"station.\"", type: "calibration" },
  { text: "Name as many adjectives for temperature as you can.", type: "calibration" },
  { text: "Describe a coin to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to reconcile a bank statement.", type: "calibration" },
  { text: "Describe a bus without using the words \"ride,\" \"stop,\" or \"pass.\"", type: "calibration" },
  { text: "Describe a dollar bill to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to write a thank-you note.", type: "calibration" },
  { text: "Describe a taxi without using the words \"ride,\" \"yellow,\" or \"meter.\"", type: "calibration" },
  { text: "Describe a credit card to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to address a formal letter.", type: "calibration" },
  { text: "Describe a skyscraper without using the words \"tall,\" \"building,\" or \"city.\"", type: "calibration" },
  { text: "Describe a receipt to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to RSVP to an invitation.", type: "calibration" },
  { text: "Describe a barn without using the words \"farm,\" \"animal,\" or \"red.\"", type: "calibration" },
  { text: "Describe a price tag to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to make a pot of coffee in a drip machine.", type: "calibration" },
  { text: "Describe a silo without using the words \"grain,\" \"farm,\" or \"tall.\"", type: "calibration" },
  { text: "Describe a shopping cart to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to brew a cup of loose-leaf tea.", type: "calibration" },
  { text: "Describe a barcode to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to pour a pint of beer from a tap.", type: "calibration" },
  { text: "Describe a cash register to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to open a bottle of wine with a corkscrew.", type: "calibration" },
  { text: "Describe a conveyor belt at checkout to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to open a wine bottle without a corkscrew.", type: "calibration" },
  { text: "Describe a paper shopping bag to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to shuck an oyster.", type: "calibration" },
  { text: "Describe a suitcase to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to de-vein a shrimp.", type: "calibration" },
  { text: "Describe a backpack strap to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fillet a fish.", type: "calibration" },
  { text: "Describe a zipper pull to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to carve a roast chicken.", type: "calibration" },
  { text: "Describe a luggage tag to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to carve a turkey.", type: "calibration" },
  { text: "Describe a passport to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to sharpen scissors.", type: "calibration" },
  { text: "Describe a boarding pass to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to clean a pair of eyeglasses properly.", type: "calibration" },
  { text: "Describe an airplane seatbelt to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to put in contact lenses.", type: "calibration" },
  { text: "Describe a tray table to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to take out contact lenses.", type: "calibration" },
  { text: "Describe an overhead bin to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to wind a mechanical watch.", type: "calibration" },
  { text: "Describe a window shade on a plane to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to set the time on an analog clock.", type: "calibration" },
  { text: "Describe a life vest to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to adjust the time on a wristwatch with a crown.", type: "calibration" },
  { text: "Describe a seat cushion on a plane to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to replace a watch battery.", type: "calibration" },
  { text: "Describe an oxygen mask to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to tie fishing line to a reel.", type: "calibration" },
  { text: "Describe an in-flight magazine to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to make popcorn on the stovetop.", type: "calibration" },
  { text: "Describe a hotel key card to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to melt chocolate in a double boiler.", type: "calibration" },
  { text: "Describe a do not disturb sign to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to toast a marshmallow for s'mores.", type: "calibration" },
  { text: "Describe an ice bucket to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to build a sandwich with the ingredients you have at home.", type: "calibration" },
  { text: "Describe a hotel coffee maker to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to assemble a burrito so it doesn't fall apart.", type: "calibration" },
  { text: "Describe a tiny shampoo bottle to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to fold a dumpling.", type: "calibration" },
  { text: "Describe a bathtub drain to someone who has never seen one.", type: "calibration" },
  { text: "Explain how to roll sushi with a bamboo mat.", type: "calibration" },
  { text: "Describe a showerhead to someone who has never seen one.", type: "calibration" },
  { text: "Describe a bathroom tile to someone who has never seen one.", type: "calibration" },
  { text: "Describe a toilet paper holder to someone who has never seen one.", type: "calibration" },
  { text: "Describe a medicine cabinet to someone who has never seen one.", type: "calibration" },
  { text: "Describe a doormat to someone who has never seen one.", type: "calibration" },
  { text: "Describe a welcome mat pattern to someone who has never seen one.", type: "calibration" },
  { text: "Describe a porch light to someone who has never seen one.", type: "calibration" },
  { text: "Describe a screen door to someone who has never seen one.", type: "calibration" },
  { text: "Describe a storm door to someone who has never seen one.", type: "calibration" },
  { text: "Describe a thermostat to someone who has never seen one.", type: "calibration" },
  { text: "Describe a smoke detector to someone who has never seen one.", type: "calibration" },
  { text: "Describe a fire extinguisher to someone who has never seen one.", type: "calibration" },
  { text: "Describe a first aid kit to someone who has never seen one.", type: "calibration" },
  { text: "Describe a flashlight battery to someone who has never seen one.", type: "calibration" },
  { text: "Describe a nine-volt battery to someone who has never seen one.", type: "calibration" },
  { text: "Describe a AAA battery to someone who has never seen one.", type: "calibration" },
  { text: "Describe a car battery terminal to someone who has never seen one.", type: "calibration" },
  { text: "Describe a jumper cable clamp to someone who has never seen one.", type: "calibration" },
  { text: "Describe a tire gauge to someone who has never seen one.", type: "calibration" },
  { text: "Describe an umbrella to someone who has never seen one.", type: "calibration" },
  { text: "Describe a raincoat hood to someone who has never seen one.", type: "calibration" },
  { text: "Describe a rubber boot to someone who has never seen one.", type: "calibration" },
  { text: "Describe a winter glove to someone who has never seen one.", type: "calibration" },
  { text: "Describe a scarf to someone who has never seen one.", type: "calibration" },
  { text: "Describe a beanie to someone who has never seen one.", type: "calibration" },
  { text: "Describe a baseball cap brim to someone who has never seen one.", type: "calibration" },
  { text: "Describe a sun visor to someone who has never seen one.", type: "calibration" },
  { text: "Describe a pair of sunglasses to someone who has never seen one.", type: "calibration" },
  { text: "Describe reading glasses to someone who has never seen one.", type: "calibration" },
  { text: "Describe a shoelace to someone who has never seen one.", type: "calibration" },
];