/**
 * Approve and insert corpus candidates from a markdown file.
 *
 * Reads a candidate file (generated by expand-corpus.ts), inserts lines
 * marked with [x] into tb_question_corpus. Idempotent on text.
 *
 * Run: npx tsx src/scripts/approve-corpus.ts data/corpus-candidates-2026-04-24.md
 */

import 'dotenv/config';
import { readFileSync } from 'node:fs';
import { insertCorpusQuestion } from '../lib/libDb.ts';

async function main(): Promise<void> {
  const filepath = process.argv[2];
  if (!filepath) {
    console.error('Usage: npx tsx src/scripts/approve-corpus.ts <candidate-file.md>');
    process.exit(1);
  }

  const content = readFileSync(filepath, 'utf-8');
  const lines = content.split('\n');

  let inserted = 0;
  let skipped = 0;
  let duplicate = 0;

  for (const line of lines) {
    // Match checked items: "- [x] Question text" or "- [X] Question text"
    const match = line.match(/^-\s*\[[xX]\]\s*(.+)$/);
    if (!match) continue;

    // match[1] is the (.+) capture group; defined whenever match itself is.
    const text = match[1]!.trim();
    if (!text) continue;

    const id = await insertCorpusQuestion({ text, added_by: 'expand-corpus' });
    if (id !== null) {
      inserted++;
      console.log(`  + [${id}] ${text}`);
    } else {
      duplicate++;
      console.log(`  = (duplicate) ${text}`);
    }
  }

  // Count unchecked items
  for (const line of lines) {
    if (/^-\s*\[\s\]\s*.+$/.test(line)) {
      skipped++;
    }
  }

  console.log(`\nDone: ${inserted} inserted, ${duplicate} duplicate, ${skipped} skipped (unchecked).`);
}

main().catch((err) => {
  console.error('approve-corpus failed:', err);
  process.exit(1);
});
