#!/usr/bin/env node
// Convert napi-derive's TYPE_DEF_TMP_PATH JSONL output to a clean index.d.ts.
//
// Why this exists: napi-derive (v2 with the `type-def` feature) emits one JSON
// line per FFI item to a temp file specified by TYPE_DEF_TMP_PATH at build
// time. The napi-rs v3 CLI's `--dts` flag isn't reliably picking this up in
// our setup (different temp path conventions between v2 derive and v3 CLI),
// so build.sh sets TYPE_DEF_TMP_PATH itself, runs cargo, then this script
// stitches the JSONL into a TypeScript declaration file.
//
// One source of truth: edit the Rust `#[napi]` annotations and the .d.ts
// regenerates. No hand-written interface to drift.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const TMP = process.argv[2];
const OUT = process.argv[3];
if (!TMP || !OUT) {
  console.error('usage: generate-dts.mjs <tmp-path> <out-path>');
  process.exit(2);
}
if (!existsSync(TMP)) {
  console.error(`type-def temp file not found: ${TMP}`);
  console.error('did you set TYPE_DEF_TMP_PATH and run cargo build?');
  process.exit(2);
}

const lines = readFileSync(TMP, 'utf-8').split('\n').filter((l) => l.trim());
const items = lines.map((l) => JSON.parse(l));

// De-duplicate: cargo may compile multiple targets, and each can append to
// the same temp file. Keep the last occurrence per (kind, name).
const dedup = new Map();
for (const it of items) {
  dedup.set(`${it.kind}:${it.name}`, it);
}

const banner = `/* eslint-disable */
/* prettier-ignore */
// Auto-generated by src-rs/scripts/generate-dts.mjs from napi-derive type-def output.
// DO NOT EDIT BY HAND. Edit the Rust #[napi] annotations and rebuild.
`;

const out = [banner];

// Interfaces first, then functions.
const interfaces = [...dedup.values()].filter((it) => it.kind === 'interface');
const fns = [...dedup.values()].filter((it) => it.kind === 'fn');

for (const it of interfaces) {
  if (it.js_doc) out.push(it.js_doc.trimEnd());
  out.push(`export interface ${it.name} {`);
  // Indent the def by two spaces; the def includes its own newlines + jsdoc.
  for (const line of it.def.split('\n')) {
    out.push(line ? `  ${line}` : '');
  }
  out.push('}');
  out.push('');
}

for (const it of fns) {
  if (it.js_doc) out.push(it.js_doc.trimEnd());
  out.push(it.def);
  out.push('');
}

writeFileSync(OUT, out.join('\n'));
console.log(`[generate-dts] wrote ${out.length} lines to ${OUT}`);
